#!/usr/bin/env bash
set -euo pipefail

REPO="${ZSHKIT_REPO:-https://github.com/theasmat/zshkit.git}"
DEST="${ZSHKIT_HOME:-$HOME/.config/zshkit}"
METHOD="${ZSHKIT_METHOD:-official}"
BIN="$HOME/.local/bin"
ZSHRC="$HOME/.zshrc"
failed=""

say()  { printf '==> %s\n' "$*"; }
warn() { printf '!!  %s\n' "$*" >&2; }
have() { command -v "$1" >/dev/null 2>&1; }

have git  || { echo "git not found" >&2; exit 1; }
have curl || { echo "curl not found" >&2; exit 1; }

mkdir -p "$BIN"
export PATH="$BIN:$HOME/.atuin/bin:$HOME/.fzf/bin:$PATH"

for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
  if [[ -x "$b" ]]; then eval "$("$b" shellenv)"; break; fi
done

installed() {
  case "$1" in
    antidote)
      [[ -r "$HOME/.antidote/antidote.zsh" ]] && return 0
      have brew && [[ -r "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh" ]]
      ;;
    *) have "$1" ;;
  esac
}

# Official install methods, taken from each project's own docs
install_starship() { curl -fsSL https://starship.rs/install.sh | sh -s -- -y -b "$BIN"; }
install_zoxide()   { curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh; }
install_mise()     { curl -fsSL https://mise.run | sh; }
install_antidote() { git clone --depth=1 https://github.com/mattmc3/antidote.git "$HOME/.antidote"; }
install_fzf() {
  if have brew; then
    brew install fzf
  else
    git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME/.fzf" && "$HOME/.fzf/install" --bin
  fi
}
# Same installer that setup.atuin.sh runs, minus its edits to ~/.zshrc
install_atuin() {
  curl --proto '=https' --tlsv1.2 -LsSf https://github.com/atuinsh/atuin/releases/latest/download/atuin-installer.sh | ATUIN_NO_MODIFY_PATH=1 sh
}

ensure() {
  local name="$1" fn="install_$1"
  if installed "$name"; then
    say "$name: already installed, skipping"
    return 0
  fi
  say "$name: installing"
  if [[ "$METHOD" == "brew" ]] && have brew; then
    brew install "$name" || { warn "$name: brew install failed"; failed="$failed $name"; }
  elif ! "$fn"; then
    warn "$name: install failed"
    failed="$failed $name"
  fi
}

say "Core tools (method: $METHOD)"
for t in starship zoxide fzf antidote mise; do ensure "$t"; done

if [[ "${ZSHKIT_MINIMAL:-0}" != "1" ]]; then
  say "Optional tools (set ZSHKIT_MINIMAL=1 to skip)"
  ensure atuin
  for pair in eza:eza bat:bat fd:fd ripgrep:rg git-delta:delta; do
    formula="${pair%%:*}"
    cmd="${pair##*:}"
    if have "$cmd"; then
      say "$formula: already installed, skipping"
    elif have brew; then
      say "$formula: installing"
      brew install "$formula" || { warn "$formula: brew install failed"; failed="$failed $formula"; }
    else
      say "$formula: skipped (needs Homebrew)"
    fi
  done
fi

if [[ -d "$DEST/.git" ]]; then
  say "Updating $DEST"
  git -C "$DEST" pull --ff-only || echo "Update skipped (local changes?)"
else
  say "Cloning zshkit to $DEST"
  mkdir -p "$(dirname "$DEST")"
  git clone --depth=1 "$REPO" "$DEST"
fi

[[ -f "$DEST/custom.zsh" ]] || printf '%s\n' '# Personal overrides (git-ignored, sourced last)' > "$DEST/custom.zsh"

if [[ -f "$ZSHRC" ]] && grep -q 'zshkit.zsh' "$ZSHRC"; then
  say "$ZSHRC already wired to zshkit"
else
  if [[ -f "$ZSHRC" ]]; then
    backup="$HOME/.zshrc.pre-zshkit-$(date +%Y%m%d%H%M%S)"
    say "Backing up $ZSHRC to $backup"
    cp "$ZSHRC" "$backup"
  fi
  printf '# Generated by zshkit\n[[ -r "%s/config/zshkit.zsh" ]] && source "%s/config/zshkit.zsh"\n' "$DEST" "$DEST" > "$ZSHRC"
fi

if [[ -n "$failed" ]]; then
  warn "These tools failed to install:$failed"
  exit 1
fi

say "Done. Restart your terminal or run: exec zsh"
