#!/usr/bin/env bash
set -euo pipefail

REPO="${ZSHKIT_REPO:-https://github.com/theasmat/zshkit.git}"
DEST="${ZSHKIT_HOME:-$HOME/.config/zshkit}"
ZSHRC="$HOME/.zshrc"

say() { printf '==> %s\n' "$*"; }

command -v brew >/dev/null || { echo "Homebrew not found: https://brew.sh" >&2; exit 1; }
command -v git >/dev/null || { echo "git not found" >&2; exit 1; }

core=(starship zoxide fzf antidote mise)
extra=(atuin eza bat fd ripgrep git-delta)

say "Installing core tools: ${core[*]}"
brew install "${core[@]}"

if [[ "${ZSHKIT_MINIMAL:-0}" != "1" ]]; then
  say "Installing optional tools (set ZSHKIT_MINIMAL=1 to skip): ${extra[*]}"
  brew install "${extra[@]}"
fi

if [[ -d "$DEST/.git" ]]; then
  say "Updating $DEST"
  git -C "$DEST" pull --ff-only || echo "Update skipped (local changes?)"
else
  say "Cloning zshkit to $DEST"
  mkdir -p "$(dirname "$DEST")"
  git clone --depth=1 "$REPO" "$DEST"
fi

[[ -f "$DEST/custom.zsh" ]] || printf '%s\n' '# Personal overrides (git-ignored, sourced last)' > "$DEST/custom.zsh"

if [[ -f "$ZSHRC" ]] && grep -q 'zshkit.zsh' "$ZSHRC"; then
  say "~/.zshrc already wired to zshkit"
else
  if [[ -f "$ZSHRC" ]]; then
    backup="$HOME/.zshrc.pre-zshkit-$(date +%Y%m%d%H%M%S)"
    say "Backing up ~/.zshrc to $backup"
    cp "$ZSHRC" "$backup"
  fi
  printf '# Generated by zshkit\n[[ -r "%s/config/zshkit.zsh" ]] && source "%s/config/zshkit.zsh"\n' "$DEST" "$DEST" > "$ZSHRC"
fi

say "Done. Restart your terminal or run: exec zsh"
